llm:
  base_url: https://api.openai.com/v1
  model_name: gpt-3.5-turbo
  api_version: ""
  agents:
    general:
      model_name: gpt-3.5-turbo
      base_url: https://api.openai.com/v1

prompts:
  agent_one:
    summary: "prompts/agent_one/summary.txt"
    followup: "prompts/agent_one/followup.txt"
